# Generated by Django 5.1.2 on 2024-10-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
