# Generated by Django 5.1.2 on 2024-11-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_file_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
