# Generated by Django 5.1.2 on 2024-11-07 13:55

import vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_folder_trashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded_file',
            field=models.FileField(upload_to=vault.models.user_directory_path),
        ),
    ]
