# Generated by Django 5.1.2 on 2026-08-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_alter_file_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='folder',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
    ]
