# Generated by Django 5.1.2 on 2026-07-30 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0004_hnsw_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('stats_snapshot', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='storageinsight',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_insight', to=settings.AUTH_USER_MODEL),
        ),
    ]

